App\Models\Doctrine\ProductCategoryTab:
    type: entity
    table: product_category_tab
    id:
        code:
            type: integer
            nullable: false
            options:
                unsigned: true
                comment: !!binary Q29kZSBkZSBsYSBjYXTpZ29yaWU=
            id: true
            column: Code
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
                comment: !!binary Tm9tIGRlIGxhIGNhdOlnb3JpZQ==
            column: Name
    lifecycleCallbacks: {  }
